//
//  Copyright (c) 2026 Jeremie Corbier
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

import XCTest
@testable import XPlaneLauncher

final class NavigraphIntegrationTests: XCTestCase {

    override func setUp() {
        super.setUp()
        UserDefaults.standard.removeObject(forKey: .customNavdataAddonMappings)
    }

    override func tearDown() {
        UserDefaults.standard.removeObject(forKey: .customNavdataAddonMappings)
        super.tearDown()
    }

    func testCycleInfoTxtParsing() {
        let sampleTxt = """
        AIRAC cycle          : 2608
        Version              : 1
        Valid (from/to)      : 06/AUG/2026 - 03/SEP/2026

        Generated by Navigraph
        """

        let scanner = NavdataScanner()
        let parsed = scanner.parseCycleInfoTxt(sampleTxt)

        XCTAssertNotNil(parsed)
        XCTAssertEqual(parsed?.cycle, "2608")
        XCTAssertEqual(parsed?.revision, "1")
        XCTAssertEqual(parsed?.airac, "06/AUG/2026 - 03/SEP/2026")
        XCTAssertEqual(parsed?.provider, "Navigraph")
    }

    func testFMSDataIndexXMLParsing() throws {
        let sampleXML = """
        <?xml version="1.0" encoding="utf-8"?>
        <addonIndexes id="8db77c8a-1059-420e-9114-4fd9d34129f3" cycle="2608" internalId="2608r1" fileRevision="2608.0727.1.0">
          <addon name="X-Plane 12" guid="17271467-ff15-4302-82a6-946b0ffe2aec" cycle="2608" revision="1" masterfile="master_xplane12_2608.zip">
            <mapping platform="ALL" simulator="XP12">
              <directory path="[SIMROOT]\\Custom Data" />
              <search>
                <filesystem path="[XP12ROOT]/Resources/default data/airspaces" filename="airspace.txt" />
              </search>
            </mapping>
          </addon>
          <addon name="FlightFactor Boeing 777v2" guid="a5b0d553-94d8-45d7-bffa-3fa87263ae5c" cycle="2608" revision="1" masterfile="master_ffb777v2_2608.zip">
            <mapping platform="ALL" simulator="XP12">
              <directory path="[SIMROOT]\\Custom Data\\STSFF\\nav-data\\ndbl\\data" />
              <search>
                <filesystem path="[XP12ROOT]\\Custom Data\\STSFF\\nav-data\\ndbl\\data" filename="cycle_info.txt" />
              </search>
            </mapping>
          </addon>
        </addonIndexes>
        """.data(using: .utf8)!

        let catalog = try FMSIndexXMLParser.parse(data: sampleXML)

        XCTAssertEqual(catalog.cycle, "2608")
        XCTAssertEqual(catalog.internalId, "2608r1")
        XCTAssertEqual(catalog.addons.count, 2)

        let xp12 = catalog.addons.first { $0.name == "X-Plane 12" }
        XCTAssertNotNil(xp12)
        XCTAssertEqual(xp12?.masterfile, "master_xplane12_2608.zip")
        XCTAssertEqual(xp12?.mappings.first?.simulator, "XP12")
        XCTAssertEqual(xp12?.mappings.first?.directoryPath, "[SIMROOT]\\Custom Data")

        let ff777 = catalog.addons.first { $0.name == "FlightFactor Boeing 777v2" }
        XCTAssertNotNil(ff777)
        XCTAssertEqual(ff777?.masterfile, "master_ffb777v2_2608.zip")
        XCTAssertEqual(ff777?.mappings.first?.directoryPath, "[SIMROOT]\\Custom Data\\STSFF\\nav-data\\ndbl\\data")
    }

    func testDefaultScanningIncludesOnlyXP12BaseAndMappedAddons() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("XPlaneLauncherTest_\(UUID().uuidString)")
        let xpDir = tempDir.appendingPathComponent("X-Plane 12")
        let centralDir = tempDir.appendingPathComponent("CentralData")

        let fileManager = FileManager.default
        try fileManager.createDirectory(at: xpDir.appendingPathComponent("Custom Data"), withIntermediateDirectories: true)

        let md11Folder = xpDir.appendingPathComponent("Aircraft/Rotate-MD-11P-x12b")
        let md11NavData = md11Folder.appendingPathComponent("nav-data")
        try fileManager.createDirectory(at: md11NavData, withIntermediateDirectories: true)
        try "test acf".write(to: md11Folder.appendingPathComponent("Rotate-MD-11.acf"), atomically: true, encoding: .utf8)
        try "AIRAC cycle : 2512\n".write(to: md11NavData.appendingPathComponent("cycle_info.txt"), atomically: true, encoding: .utf8)

        let md11Addon = FMSAddonDefinition(
            name: "Rotate MD-11 Passenger",
            guid: "md11-guid",
            cycle: "2608",
            revision: "1",
            masterfile: "master_rotate_md11_2608.zip",
            mappings: [
                FMSAddonMapping(
                    platform: "ALL",
                    simulator: "XP12",
                    directoryPath: "[SIMROOT]\\Aircraft\\Rotate-MD-11P-x12b\\nav-data",
                    searches: [
                        FMSAddonSearchEntry(path: "[XP12ROOT]\\Aircraft\\Rotate-MD-11P-x12b", filename: "Rotate-MD-11.acf")
                    ]
                )
            ]
        )

        let catalog = FMSCatalog(
            id: "cat1",
            cycle: "2608",
            internalId: "2608r1",
            fileRevision: "2608.1",
            addons: [
                FMSAddonDefinition(
                    name: "X-Plane 12",
                    guid: "xp12-guid",
                    cycle: "2608",
                    revision: "1",
                    masterfile: "master_xplane12_2608.zip",
                    mappings: [
                        FMSAddonMapping(platform: "ALL", simulator: "XP12", directoryPath: "[SIMROOT]\\Custom Data")
                    ]
                ),
                md11Addon
            ]
        )

        let scanner = NavdataScanner()

        // 1. By default, only base X-Plane 12 is scanned
        let initialItems = scanner.scanAddons(xPlaneURL: xpDir, launcherDataFolder: centralDir, catalog: catalog)
        XCTAssertEqual(initialItems.count, 1, "Only base X-Plane 12 should be included by default")
        XCTAssertEqual(initialItems.first?.definition.name, "X-Plane 12")

        // 2. Test suggested path computation for Rotate MD-11
        let suggested = scanner.computeSuggestedPath(for: md11Addon, xPlaneURL: xpDir, launcherDataFolder: centralDir)
        XCTAssertEqual(suggested, "Aircraft/Rotate-MD-11P-x12b/nav-data")

        // 3. Save mapping for Rotate MD-11
        let md11Mapping = NavdataAddonDefinition(
            id: md11Addon.guid,
            name: md11Addon.name,
            formatKey: "rotate-md-11",
            relativeTargetPath: suggested,
            masterfile: md11Addon.masterfile,
            isCustom: true
        )
        NavdataCatalog.saveCustomAddon(md11Mapping)

        // 4. Now both X-Plane 12 and Rotate MD-11 should be listed
        let itemsWithMapping = scanner.scanAddons(xPlaneURL: xpDir, launcherDataFolder: centralDir, catalog: catalog)
        XCTAssertEqual(itemsWithMapping.count, 2)
        let md11Item = itemsWithMapping.first { $0.id == "md11-guid" }
        XCTAssertNotNil(md11Item)
        XCTAssertTrue(md11Item!.isInstalled)
        XCTAssertEqual(md11Item!.currentCycle, "2512")
        XCTAssertEqual(md11Item!.latestCycle, "2608")
        XCTAssertTrue(md11Item!.isUpdateAvailable)

        try? fileManager.removeItem(at: tempDir)
    }

    func testFMSCurrentCycleLiveEndpoint() async throws {
        let url = URL(string: "https://www.navigraph.com/api/1/fmsdata/cycles/current")!
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue("Mozilla/5.0", forHTTPHeaderField: "User-Agent")

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            XCTFail("Response was not an HTTPURLResponse")
            return
        }

        XCTAssertEqual(http.statusCode, 200, "Current cycle endpoint should return HTTP 200")
        let cycleInfo = try JSONDecoder().decode(FMSCycleInfo.self, from: data)
        XCTAssertFalse(cycleInfo.cycle.isEmpty)
        XCTAssertFalse(cycleInfo.cycleInternalId.isEmpty)
    }

    func testFMSDataIndexMetadataLiveEndpoint() async throws {
        let url = URL(string: "https://www.navigraph.com/api/1/fmsdata/index")!
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue("Mozilla/5.0", forHTTPHeaderField: "User-Agent")

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            XCTFail("Response was not an HTTPURLResponse")
            return
        }

        XCTAssertEqual(http.statusCode, 200)

        struct IndexMeta: Codable {
            let Id: String
            let Url: String
        }

        let meta = try JSONDecoder().decode(IndexMeta.self, from: data)
        XCTAssertFalse(meta.Id.isEmpty)
        XCTAssertTrue(meta.Url.contains("data.index"))
    }

    func testFMSPackageIndexParser() throws {
        let sampleIndexXML = """
        <?xml version="1.0" encoding="utf-8"?>
        <addon name="FlightFactor Boeing 777v2" guid="a5b0d553-94d8-45d7-bffa-3fa87263ae5c" cycle="2608" revision="1">
          <mapping simulator="XP11">
            <directory name=".">
              <files destination="cycle_info.txt" source="f04cd083-25bd-4205-8856-289d687ed165" />
            </directory>
          </mapping>
          <mapping simulator="XP12">
            <directory name=".">
              <files destination="cycle_info.txt" source="f04cd083-25bd-4205-8856-289d687ed165" />
              <files destination="cycle.json" source="e57e20fb-744f-4dcd-adbf-615b176f8d67" />
              <files destination="nav1.db" source="bffea478-80b0-415b-b096-cca535c6cccc" />
              <files destination="nav2.db" source="f32ff43c-f335-487b-ba12-ab20e21ea274" />
            </directory>
          </mapping>
        </addon>
        """.data(using: .utf8)!

        let packageIndex = try FMSPackageIndexParser.parse(data: sampleIndexXML, simulator: "XP12")
        XCTAssertEqual(packageIndex.addonName, "FlightFactor Boeing 777v2")
        XCTAssertEqual(packageIndex.guid, "a5b0d553-94d8-45d7-bffa-3fa87263ae5c")
        XCTAssertEqual(packageIndex.cycle, "2608")
        XCTAssertEqual(packageIndex.fileMappings.count, 4)

        let cycleInfoMapping = packageIndex.fileMappings.first { $0.destination == "cycle_info.txt" }
        XCTAssertNotNil(cycleInfoMapping)
        XCTAssertEqual(cycleInfoMapping?.source, "f04cd083-25bd-4205-8856-289d687ed165")

        let nav1Mapping = packageIndex.fileMappings.first { $0.destination == "nav1.db" }
        XCTAssertNotNil(nav1Mapping)
        XCTAssertEqual(nav1Mapping?.source, "bffea478-80b0-415b-b096-cca535c6cccc")
    }

    @MainActor
    func testAuthSignOutClearsState() {
        let auth = NavigraphAuthManager()
        auth.signOut()
        XCTAssertEqual(auth.authState, .unauthenticated)
        XCTAssertNil(auth.token)
        XCTAssertNil(auth.currentUser)
    }
}
